// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Sidebar principal con índice y resumen de todos los temas
  mainSidebar: [
    'index',
  ],
  
  // Sidebar específico para Tema 1 - Autogenerado
  tema1Sidebar: [
    {
      type: 'autogenerated',
      dirName: 'tema1-multitarea',
    },
  ],
  
  // Sidebar específico para Tema 2 - Autogenerado
  tema2Sidebar: [
    {
      type: 'autogenerated',
      dirName: 'tema2-hilos',
    },
  ],
  
  // Sidebar específico para Tema 3 - Autogenerado
  tema3Sidebar: [
    {
      type: 'autogenerated',
      dirName: 'tema3-sincronizacion',
    },
  ],
  
  // Sidebar específico para Tema 4 - Autogenerado
  tema4Sidebar: [
    {
      type: 'autogenerated',
      dirName: 'tema4-comunicacion-procesos',
    },
  ],
  
  // Sidebar específico para Tema 5 - Autogenerado
  tema5Sidebar: [
    {
      type: 'autogenerated',
      dirName: 'tema5-red',
    },
  ],
  
  // Sidebar específico para Tema 6 - Autogenerado
  tema6Sidebar: [
    {
      type: 'autogenerated',
      dirName: 'tema6-servicios-red',
    },
  ],
  
  // Sidebar específico para Tema 7 - Autogenerado
  tema7Sidebar: [
    {
      type: 'autogenerated',
      dirName: 'tema7-seguridad',
    },
  ],
};

export default sidebars;
