
const sidebars = {
  // Sidebar principal con índice y resumen de todos los temas
  mainSidebar: [
    'index',
    'formato-entregas'
  ],

  //Sidebar especifico para Tema 0 - Autogenerado
  tema0Sidebar: [
    {
      type: 'autogenerated',
      dirName: 'tema0-kotlin',
    },
  ],

  // Sidebar específico para Tema 1 - Autogenerado
  tema1Sidebar: [
    {
      type: 'autogenerated',
      dirName: 'tema1-fundamentos',
    },
  ],
  
  // Sidebar específico para Tema 2 - Autogenerado
  tema2Sidebar: [
    {
      type: 'autogenerated',
      dirName: 'tema2-multihilo',
    },
  ],
  
  // Sidebar específico para Tema 3 - Autogenerado
  tema3Sidebar: [
    {
      type: 'autogenerated',
      dirName: 'tema3-comunicaciones-red',
    },
  ],
  
  // Sidebar específico para Tema 4 - Autogenerado
  tema4Sidebar: [
    {
      type: 'autogenerated',
      dirName: 'tema4-servicios-seguridad',
    },
  ],
};

export default sidebars;
